<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Model;

use Dealer\Model\Base\DealerTab as BaseDealerTab;

/**
 * Class DealerTab
 * @package Dealer\Model
 */
class DealerTab extends BaseDealerTab
{
}
