<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Action;

use Dealer\Action\Base\DealerTabAction as  BaseDealerTabAction;

/**
 * Class DealerTabAction
 * @package Dealer\Action
 */
class DealerTabAction extends BaseDealerTabAction
{
}
