<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Form\Type;

use Dealer\Form\Type\Base\DealerTabIdType as BaseDealerTabIdType;

/**
 * Class DealerTab
 * @package Dealer\Form
 */
class DealerTabIdType extends BaseDealerTabIdType
{
}
