<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Event;

use Dealer\Event\Base\DealerTabEvents as BaseDealerTabEvents;

/**
 * Class DealerTabEvents
 * @package Dealer\Event
 */
class DealerTabEvents extends BaseDealerTabEvents
{
}
