<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Event;

use Dealer\Event\Base\DealerEvents as BaseDealerEvents;

/**
 * Class DealerEvents
 * @package Dealer\Event
 * @author TheliaStudio
 */
class DealerEvents extends BaseDealerEvents
{
}
