<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Event;

use Dealer\Event\Base\DealerTabEvent as BaseDealerTabEvent;

/**
 * Class DealerTabEvent
 * @package Dealer\Event
 */
class DealerTabEvent extends BaseDealerTabEvent
{
}
