<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Form\Base;

use Dealer\Form\DealerTabCreateForm as ChildDealerTabCreateForm;
use Dealer\Form\Type\DealerTabIdType;

/**
 * Class DealerTabForm
 * @package Dealer\Form
 * @author TheliaStudio
 */
class DealerTabUpdateForm extends ChildDealerTabCreateForm
{
    const FORM_NAME = "dealer_tab_update";

    public function buildForm()
    {
        parent::buildForm();

        $this->formBuilder
            ->add("id", DealerTabIdType::TYPE_NAME)
        ;
    }
}
