<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Loop;

use Dealer\Loop\Base\DealerTab as BaseDealerTabLoop;

/**
 * Class DealerTab
 * @package Dealer\Loop
 */
class DealerTab extends BaseDealerTabLoop
{
    /**
     * You may now add your own logic
     */
}
