<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Form;

use Dealer\Form\Base\DealerTabUpdateForm as BaseDealerTabUpdateForm;

/**
 * Class DealerTabUpdateForm
 * @package Dealer\Form
 */
class DealerTabUpdateForm extends BaseDealerTabUpdateForm
{
    public function getTranslationKeys()
    {
        return array(
            "id" => "id",
            "company" => "company",
            "address1" => "address1",
            "address2" => "address2",
            "zipcode" => "zipcode",
            "city" => "city",
            "description" => "description",
            "schedule" => "schedule",
            "phone_number" => "phone_number",
            "web_site" => "web_site",
            "latitude" => "latitude",
            "longitude" => "longitude",
        );
    }
}
