<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Form;

use Dealer\Form\Base\DealerTabCreateForm as BaseDealerTabCreateForm;

/**
 * Class DealerTabCreateForm
 * @package Dealer\Form
 */
class DealerTabCreateForm extends BaseDealerTabCreateForm
{
    public function getTranslationKeys()
    {
        return array(
            "company" => "Company",
            "address1" => "Address1",
            "address2" => "Address2",
            "zipcode" => "Zipcode",
            "city" => "City",
            "description" => "Description",
            "schedule" => "Schedule",
            "phone_number" => "Phone number",
            "web_site" => "Web site",
            "latitude" => "Latitude",
            "longitude" => "Longitude",
        );
    }
}
