<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Event\Base;

/**
 * Class DealerEvents
 * @package Dealer\Event\Base
 * @author TheliaStudio
 */
class DealerEvents
{
    const DEALER_TAB_CREATE = "action.dealer_tab.create";
    const DEALER_TAB_UPDATE = "action.dealer_tab.update";
    const DEALER_TAB_DELETE = "action.dealer_tab.delete";
}
