<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Event\Base;

use Dealer\Event\DealerEvents as ChildDealerEvents;

/*
 * Class DealerTabEvents
 * @package Dealer\Event\Base
 * @author TheliaStudio
 */
class DealerTabEvents
{
    const CREATE = ChildDealerEvents::DEALER_TAB_CREATE;
    const UPDATE = ChildDealerEvents::DEALER_TAB_UPDATE;
    const DELETE = ChildDealerEvents::DEALER_TAB_DELETE;
}
