<?php
/**
* This class has been generated by TheliaStudio
* For more information, see https://github.com/thelia-modules/TheliaStudio
*/

namespace Dealer\Form\Type\Base;

use Thelia\Core\Form\Type\Field\AbstractIdType;
use Dealer\Model\DealerTabQuery;

/**
 * Class DealerTab
 * @package Dealer\Form\Base
 * @author TheliaStudio
 */
class DealerTabIdType extends AbstractIdType
{
    const TYPE_NAME = "dealer_tab_id";

    protected function getQuery()
    {
        return new DealerTabQuery();
    }

    public function getName()
    {
        return static::TYPE_NAME;
    }
}
