<?php
/**
 * This class has been generated by TheliaStudio
 * For more information, see https://github.com/thelia-modules/TheliaStudio
 */

namespace Dealer\Controller;

use Dealer\Controller\Base\DealerTabController as BaseDealerTabController;

/**
 * Class DealerTabController
 * @package Dealer\Controller
 */
class DealerTabController extends BaseDealerTabController
{
}
